"""Fix all 185 Arabic SAME_AS_KEY entries with proper Arabic translations."""
with open('C:/Users/sdads/WHDASH/translations.py', 'r', encoding='utf-8') as f:
    lines = f.read().split('\n')

AR_FIXES = {
    # Quick Tools
    'add_current_page': 'إضافة الصفحة الحالية',
    'add_favorite': 'إضافة إلى المفضلة',
    'add_favorites_hint': 'انقر + لإضافة صفحات',
    'add_note': 'إضافة ملاحظة',
    'add_reminder': 'إضافة تذكير',
    'autosave_notes': 'حفظ تلقائي للملاحظات',
    'backspace': 'مسح',
    'biweekly': 'أسبوعان',
    'bookmark_added': 'تمت إضافة الإشارة المرجعية',
    'bookmark_removed': 'تمت إزالة الإشارة المرجعية',
    'calculator': 'الآلة الحاسبة',
    'clear': 'مسح',
    'close_tools': 'إغلاق الأدوات',
    'compact_mode': 'الوضع المضغوط',
    'copy_result': 'نسخ النتيجة',
    'create_issue': 'إنشاء مشكلة',
    'create_task': 'إنشاء مهمة',
    'daily': 'يومي',
    'delete_note': 'حذف الملاحظة',
    'division_by_zero': 'لا يمكن القسمة على صفر',
    'edit_note': 'تعديل الملاحظة',
    'edit_reminder': 'تعديل التذكير',
    'equals': 'يساوي',
    'expression_error': 'خطأ في التعبير',
    'favorites': 'المفضلة',
    'in_1_hour': 'خلال ساعة واحدة',
    'invalid_expression': 'تعبير غير صالح',
    'issue_category': 'فئة المشكلة',
    'issue_created': 'تم إنشاء المشكلة',
    'issue_description': 'وصف المشكلة',
    'issue_priority': 'أولوية المشكلة',
    'issue_title': 'عنوان المشكلة',
    'issue_type': 'نوع المشكلة',
    'mark_done': 'تحديد كمكتمل',
    'next_week': 'الأسبوع القادم',
    'no_favorites': 'لا توجد مفضلات',
    'no_favorites_desc': 'لم تتم إضافة أي صفحة إلى المفضلة',
    'no_notes': 'لا توجد ملاحظات',
    'no_notes_desc': 'لم يتم حفظ أي ملاحظة',
    'no_reminders': 'لا توجد تذكيرات',
    'no_reminders_desc': 'لم يتم تعيين أي تذكير',
    'note_placeholder': 'اكتب ملاحظتك...',
    'open_tools': 'فتح الأدوات',
    'pin_note': 'تثبيت الملاحظة',
    'priority_critical': 'حرج',
    'priority_high': 'عالي',
    'priority_low': 'منخفض',
    'priority_medium': 'متوسط',
    'remind_at': 'تذكير في',
    'remind_me': 'ذكرني',
    'reminder_set': 'تم تعيين التذكير',
    'reminders': 'التذكيرات',
    'remove_favorite': 'إزالة من المفضلة',
    'result_copied': 'تم نسخ النتيجة',
    'shortcuts': 'الاختصارات',
    'show_calculator': 'إظهار الآلة الحاسبة',
    'show_favorites': 'إظهار المفضلة',
    'show_issues': 'إظهار المشاكل',
    'show_notes': 'إظهار الملاحظات',
    'show_reminders': 'إظهار التذكيرات',
    'show_tasks': 'إظهار المهام',
    'snooze': 'تأجيل',
    'snooze_1_hour': 'تأجيل ساعة واحدة',
    'task_assign_self': 'تعيين لنفسي',
    'task_assign_to': 'تعيين إلى',
    'task_created': 'تم إنشاء المهمة بنجاح',
    'task_description': 'الوصف',
    'task_due_date': 'تاريخ الاستحقاق',
    'task_priority': 'الأولوية',
    'task_title': 'عنوان المهمة',
    'tomorrow': 'غداً',
    'tonight': ' الليلة',
    'tools_calculations': 'العمليات الحسابية',
    'tools_favorites': 'المفضلة',
    'tools_issues': 'المشاكل',
    'tools_notes': 'الملاحظات',
    'tools_reminders': 'التذكيرات',
    'tools_settings': 'الإعدادات',
    'tools_tasks': 'المهام',
    'type_issue': 'اكتب المشكلة',
    'type_problem': 'مشكلة:',
    'type_suggestion': 'اقتراح:',
    'unpin_note': 'إلغاء تثبيت الملاحظة',
    # Flow - Enterprise Communication
    'flow': 'جرية',
    'flow_add_members': 'إضافة أعضاء',
    'flow_admin': 'مدير',
    'flow_all_caught_up': 'لقد اطلعت على جميع الرسائل!',
    'flow_app_name': 'جرية',
    'flow_appear_offline': 'الظهور غير متصل',
    'flow_audio_call': 'مكالمة صوتية',
    'flow_auto_reply': 'الرد التلقائي',
    'flow_away': 'بعيد',
    'flow_busy': 'مشغول',
    'flow_calls': 'المكالمات',
    'flow_category': 'الفئة',
    'flow_channels': 'القنوات',
    'flow_chat': 'محادثة',
    'flow_co_host': 'المضيف المشارك',
    'flow_copy': 'نسخ',
    'flow_create_channel': 'إنشاء قناة',
    'flow_create_first_channel': 'أنشئ قناتك الأولى لبدء التعاون',
    'flow_create_first_group': 'أنشئ مجموعة للتعاون مع فريقك',
    'flow_create_group': 'إنشاء مجموعة',
    'flow_created_by': 'أنشئ بواسطة',
    'flow_delete': 'حذف',
    'flow_delete_for_everyone': 'حذف للجميع',
    'flow_delete_for_me': 'حذف لنفسي',
    'flow_description': 'الوصف',
    'flow_edit': 'تعديل',
    'flow_editing': 'جارٍ التعديل',
    'flow_enter_send': 'Enter للإرسال',
    'flow_file_too_large': 'الملف كبير جداً (الحد الأقصى 2 جيجابايت)',
    'flow_forward': 'إعادة توجيه',
    'flow_group': 'المجموعة',
    'flow_groups': 'المجموعات',
    'flow_host': 'المضيف',
    'flow_image': 'صورة',
    'flow_in_meeting': 'في اجتماع',
    'flow_invite': 'دعوة',
    'flow_join_channel': 'الانضمام للقناة',
    'flow_join_meeting': 'الانضمام للاجتماع',
    'flow_last_seen': 'آخر ظهور',
    'flow_leave_channel': 'مغادرة القناة',
    'flow_leave_group': 'مغادرة المجموعة',
    'flow_leave_meeting': 'مغادرة الاجتماع',
    'flow_mark_read': 'تحديد كمقروء',
    'flow_media_hint': 'ستظهر الوسائط المشتركة في دردشاتك هنا',
    'flow_meetings': 'الاجتماعات',
    'flow_member': 'عضو',
    'flow_members': 'الأعضاء',
    'flow_message_deleted': 'محذوف',
    'flow_message_edited': 'معدل',
    'flow_messages': 'الرسائل',
    'flow_mute': 'كتم الصوت',
    'flow_new_chat': 'محادثة جديدة',
    'flow_no_calls': 'لا يوجد سجل مكالمات',
    'flow_no_channels': 'لا توجد قنوات بعد',
    'flow_no_conversations': 'لا توجد محادثات بعد',
    'flow_no_groups': 'لا توجد مجموعات بعد',
    'flow_no_media': 'لا توجد وسائط بعد',
    'flow_no_meetings': 'لا توجد اجتماعات',
    'flow_no_messages': 'لا توجد رسائل بعد',
    'flow_no_notifications': 'لا توجد إشعارات',
    'flow_no_reminders': 'لا توجد تذكيرات نشطة',
    'flow_no_results': 'لم يتم العثور على نتائج',
    'flow_no_saved': 'لا توجد رسائل محفوظة',
    'flow_notifications': 'الإشعارات',
    'flow_offline': 'غير متصل',
    'flow_online': 'متصل',
    'flow_online_status': 'حالة الاتصال',
    'flow_owner': 'المالك',
    'flow_participants': 'المشاركون',
    'flow_private_channel': 'قناة خاصة',
    'flow_private_chats': 'المحادثات الخاصة',
    'flow_private_group': 'مجموعة خاصة',
    'flow_profile': 'الملف الشخصي',
    'flow_public_channel': 'قناة عامة',
    'flow_public_group': 'مجموعة عامة',
    'flow_react': 'رد فعل',
    'flow_read': 'مقروء',
    'flow_recent': 'الأخيرة',
    'flow_reminder_set': 'تم تعيين التذكير',
    'flow_reminder_you_will_be_notified': 'سيتم إخطارك',
    'flow_reminders': 'التذكيرات',
    'flow_remove_member': 'إزالة العضو',
    'flow_reply': 'رد',
    'flow_reply_to': 'الرد على',
    'flow_save': 'حفظ',
    'flow_save_hint': 'احفظ الرسائل المهمة للعثور عليها لاحقاً',
    'flow_saved_messages': 'الرسائل المحفوظة',
    'flow_search': 'بحث',
    'flow_send': 'إرسال',
    'flow_send_first_message': 'أرسل رسالة لبدء المحادثة',
    'flow_set_reminder': 'تعيين تذكير',
    'flow_set_reminders_hint': 'عيّن تذكيرات على الرسائل ليتم إخطارك لاحقاً',
    'flow_settings': 'الإعدادات',
    'flow_share_screen': 'مشاركة الشاشة',
    'flow_shared_media': 'الوسائط المشتركة',
    'flow_shift_enter': 'Shift + Enter لسطر جديد',
    'flow_start_call_hint': 'ابدأ مكالمة من أي محادثة',
    'flow_start_instant_meeting': 'بدء اجتماع فوري',
    'flow_start_meeting_hint': 'ابدأ اجتماعاً فورياً',
    'flow_start_new_chat': 'ابدأ محادثة جديدة لبدء المراسلة',
    'flow_status_message': 'رسالة الحالة',
    'flow_stop_sharing': 'إيقاف المشاركة',
    'flow_stopped': 'متوقف',
    'flow_subtitle': 'الاتصال المؤسسي',
    'flow_try_different': 'جرب كلمات أو فلاتر مختلفة',
    'flow_type_message': 'اكتب رسالة...',
    'flow_typing': 'جارٍ الكتابة...',
    'flow_unmute': 'إلغاء كتم الصوت',
    'flow_upload_error': 'فشل الرفع',
    'flow_upload_file': 'رفع ملف',
    'flow_video_call': 'مكالمة فيديو',
    'flow_video_off': 'الكاميرا مغلقة',
    'flow_video_on': 'الكاميرا مفتوحة',
    'flow_visibility': 'الرؤية',
    'flow_voice_note': 'ملاحظة صوتية',
    'flow_voice_note_recording': 'جارٍ التسجيل...',
    'flow_you_were_removed': 'تمت إزالتك',
    # Quick tools
    'quick_issue': 'مشكلة سريعة',
    'quick_nav': 'تنقل سريع',
    'quick_note': 'ملاحظة سريعة',
    'quick_notes': 'ملاحظات سريعة',
    'quick_reminder': 'تذكير سريع',
    'quick_task': 'مهمة سريعة',
    'quick_tools': 'أدوات سريعة',
    'quick_tools_panel': 'لوحة الأدوات السريعة',
}

fa_start = None
for i, line in enumerate(lines):
    if line.strip().startswith("'ar':"):
        fa_start = i
        break

changes = 0
for i in range(fa_start, min(fa_start + 1000, len(lines))):
    line = lines[i]
    stripped = line.strip()
    for key, ar_val in AR_FIXES.items():
        if stripped.startswith(f"'{key}':"):
            indent = len(line) - len(line.lstrip())
            new_line = f"{' ' * indent}'{key}': '{ar_val}',"
            lines[i] = new_line
            changes += 1
            break
    if "'ru':" in lines[i]:
        break

print(f"Fixed {changes} Arabic keys")

with open('C:/Users/sdads/WHDASH/translations.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))