ISSUE_SEED_DATA = [
    # ── Original open issues ──
    {'row_id': 1, 'issue_date': '04/09/2025', 'issue': 'رسیدن به انبارگردانی لحظه ای در انبار سداد', 'pareto_law': False, 'involved_departments': 'Accounting/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open', 'responsible_section': 'Warehouse', 'responsible_person': 'Ali', 'impact': 'Real-time inventory accuracy is below 80%. Stockouts and overstock situations occur frequently causing financial loss.', 'root_cause': '', 'action_plan': '', 'target_resolution_date': '2025-12-31'},
    {'row_id': 2, 'issue_date': '15/09/2025', 'issue': 'رفتن به مرخصی نیروها بدون اطلاع قبلی یا صبح همان روز', 'pareto_law': False, 'involved_departments': 'HR/Management', 'issue_type': 'Suggestion', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 3, 'issue_date': '15/09/2025', 'issue': 'راه نیفتادن جبل علی', 'pareto_law': False, 'involved_departments': 'Management', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 4, 'issue_date': '19/09/2025', 'issue': 'تقلیل خواسته‌ها و دغدغه‌ها به سطحی بسیار کم', 'pareto_law': False, 'involved_departments': 'HR/Management', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 5, 'issue_date': '19/09/2025', 'issue': 'عدم فکر کردن به رویه و تسلط به اون', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 6, 'issue_date': '20/09/2025', 'issue': 'نداشتن خروج و فروش در فروشگاه سداد', 'pareto_law': False, 'involved_departments': 'Sales/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 7, 'issue_date': '20/09/2025', 'issue': 'تعدد زیاد ثبت فاکتور فروش اشتباه و تبعات مالیاتی', 'pareto_law': False, 'involved_departments': 'Accounting/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 8, 'issue_date': '25/09/2025', 'issue': 'عدم تقسیم کار و واگذاری اون در بخش های مختلف', 'pareto_law': False, 'involved_departments': 'Management', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 9, 'issue_date': '25/09/2025', 'issue': 'نفرستادن گزارش فروش', 'pareto_law': False, 'involved_departments': 'Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 10, 'issue_date': '25/09/2025', 'issue': 'مشکل عدم پرداخت جنس بدون وت توسط مشتری', 'pareto_law': False, 'involved_departments': 'Sales/Accounting', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 11, 'issue_date': 'Past', 'issue': 'عدم ارسال به موقع سفارشات', 'pareto_law': False, 'involved_departments': 'Delivery', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 12, 'issue_date': 'Past', 'issue': 'انتقال بار از جبل علی به رأس‌الخور و کمبود اقلام', 'pareto_law': False, 'involved_departments': 'Procurement/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 13, 'issue_date': 'Past', 'issue': 'بار بدون هماهنگی به انبار ارسال می‌شود', 'pareto_law': False, 'involved_departments': 'Sales/Warehouse/Delivery', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 14, 'issue_date': 'Past', 'issue': 'دلیوری اقلام بدون هماهنگی', 'pareto_law': False, 'involved_departments': 'Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 15, 'issue_date': 'Past', 'issue': 'دلیوری نشدن منظم بار العربین', 'pareto_law': False, 'involved_departments': 'Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 16, 'issue_date': 'Past', 'issue': 'مشکل زمان‌بر بودن چک و انتقالی بارهای جبل علی', 'pareto_law': False, 'involved_departments': 'Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 17, 'issue_date': 'Past', 'issue': 'تحویل گرفتن بار مشتری توسط راننده بدون اعلام به فروش', 'pareto_law': False, 'involved_departments': 'Sales/Warehouse/Delivery', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 18, 'issue_date': 'Past', 'issue': 'فروشنده در جریان نیست که بار دریافتی الیز در انبار موجود است', 'pareto_law': False, 'involved_departments': 'Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 19, 'issue_date': 'Past', 'issue': 'ارسال بار شارجه با تأخیر', 'pareto_law': False, 'involved_departments': 'Delivery', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 20, 'issue_date': 'Past', 'issue': 'عدم ارسال اطلاعات کامل و صحیح در درخواست بسته‌بندی', 'pareto_law': False, 'involved_departments': 'Sales/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 21, 'issue_date': 'Past', 'issue': 'اشتباه در فاکتور فروش', 'pareto_law': False, 'involved_departments': 'Sales/Accounting', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 22, 'issue_date': 'Past', 'issue': 'کالا برای مشتری فاکتور می‌شود اما در گروه اطلاع‌رسانی ثبت نمی‌شود', 'pareto_law': False, 'involved_departments': 'Sales/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 23, 'issue_date': 'Past', 'issue': 'فاکتور مشتری ارسال نشده یا بدون پکینگ لیست', 'pareto_law': False, 'involved_departments': 'Sales/Delivery/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 24, 'issue_date': 'Past', 'issue': 'فروشنده مطمئن نیست که تمام بار جدید فاکتور شده یا خیر', 'pareto_law': False, 'involved_departments': 'Procurement/Warehouse/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 25, 'issue_date': 'Past', 'issue': 'فروش اقلام برگشتی به مشتری به‌جای برگشت به تأمین‌کننده', 'pareto_law': False, 'involved_departments': 'Warehouse/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 26, 'issue_date': 'Past', 'issue': 'شفاف نبودن اعمال هزینه حمل', 'pareto_law': False, 'involved_departments': 'Procurement/Sales/Accounting/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 27, 'issue_date': 'Past', 'issue': 'پر نکردن به‌موقع اطلاعات فروش درهم در گوگل شیت', 'pareto_law': False, 'involved_departments': 'Sales/Accounting', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 28, 'issue_date': 'Past', 'issue': 'اطلاعات مشتری جدید با تأخیر', 'pareto_law': False, 'involved_departments': 'Accounting/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 29, 'issue_date': 'Past', 'issue': 'فایل برگشتی فطیم به‌اشتباه پر شده', 'pareto_law': False, 'involved_departments': 'Warehouse/Sales/Accounting', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 30, 'issue_date': 'Past', 'issue': 'استعلام قیمت جبل علی با پاسخ دیر', 'pareto_law': False, 'involved_departments': 'Sales/Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 31, 'issue_date': 'Past', 'issue': 'دیر دلیوری شدن اقلام خرید', 'pareto_law': False, 'involved_departments': 'Procurement', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 32, 'issue_date': 'Past', 'issue': 'تعدد زیاد غیبت کارکنان', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 33, 'issue_date': 'Past', 'issue': 'برگشت بار روغن توسط المکرم به‌دلیل بسته‌بندی آسیب‌دیده', 'pareto_law': False, 'involved_departments': 'Delivery/Warehouse/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 34, 'issue_date': 'Past', 'issue': 'مشکل عدم برگشت کولانت میتسوبیشی', 'pareto_law': False, 'involved_departments': 'Procurement/Sales/Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 35, 'issue_date': 'Past', 'issue': 'دیر اطلاع دادن صراف و در دسترس نبودن در روزهای کلیدی', 'pareto_law': False, 'involved_departments': 'Sales/Accounting', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 36, 'issue_date': 'Past', 'issue': 'مشکل عدم پرداخت توسط مشتری الرتبه', 'pareto_law': False, 'involved_departments': 'Accounting/Sales', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': '-', 'priority': 'High', 'status': 'Open'},
    {'row_id': 37, 'issue_date': '13/10/2025', 'issue': 'نداشتن دیتای بازار در مناطق صنعتی', 'pareto_law': False, 'involved_departments': 'Sales/Marketing', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 38, 'issue_date': '13/10/2025', 'issue': 'جذب نیروی جبل علی - عفراء', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Issue', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 39, 'issue_date': '13/10/2025', 'issue': 'جذب نیروی سوپروایزر انبار', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Issue', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 40, 'issue_date': '13/10/2025', 'issue': 'پر نشدن گوگل شیت مشکلات', 'pareto_law': False, 'involved_departments': 'All', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Iman', 'priority': 'High', 'status': 'Open'},
    {'row_id': 41, 'issue_date': '22/10/2025', 'issue': 'عدم ثبت کامل دستگاه اثر انگشت توسط پرسنل', 'pareto_law': False, 'involved_departments': 'All', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'Soroosh', 'priority': 'Medium', 'status': 'Open'},
    {'row_id': 42, 'issue_date': '10/11/2025', 'issue': 'طولانی بودن زمان آموزش پرسنل انبار', 'pareto_law': False, 'involved_departments': 'Warehouse', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 43, 'issue_date': '10/11/2025', 'issue': 'پیدا نشدن نیروی جبل علی - لوجیستیک', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Issue', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 44, 'issue_date': '24/12/2025', 'issue': 'غیبت بی اطلاع فرد و متوجه شدن در هنگام غیبت', 'pareto_law': False, 'involved_departments': 'HR', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 45, 'issue_date': '19/11/2025', 'issue': 'جریمه شدن بچه های شرکت با ماشین شرکت', 'pareto_law': False, 'involved_departments': 'All', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 46, 'issue_date': '24/02/2026', 'issue': 'مرخصی یک ماهه افراد و تاثیر اون روی کار', 'pareto_law': False, 'involved_departments': 'HR/All', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},
    {'row_id': 47, 'issue_date': '25/02/2026', 'issue': 'مشکل عدم تطبیق شماره فنی و HS Code - عفراء', 'pareto_law': False, 'involved_departments': 'Logistics', 'issue_type': 'Problem', 'writer': 'MMD', 'reported_by': 'MMD', 'priority': 'High', 'status': 'Open'},

    # ── In Progress issues ──
    {
        'row_id': 48, 'issue_date': '01/03/2026',
        'issue': 'Warehouse picker error rate exceeds 3% threshold',
        'pareto_law': True, 'involved_departments': 'Warehouse/Quality',
        'issue_type': 'Problem', 'writer': 'Sarah', 'reported_by': 'QC Team',
        'priority': 'High', 'status': 'In Progress',
        'responsible_section': 'Warehouse', 'responsible_person': 'Ali',
        'section_team': 'WMS Team',
        'impact': 'Customer returns and complaints increased by 18%. Estimated AED 12,000/month rework cost.',
        'root_cause': 'Insufficient scan verification step in pick-pack workflow. Pickers skip barcode confirmation under time pressure.',
        'action_plan': '1. Add mandatory scan confirm gate in WMS\n2. Implement picker performance dashboard\n3. Daily accuracy report to supervisor',
        'resources_needed': 'WMS developer, 2 weeks',
        'target_resolution_date': '2026-04-30',
        'progress_note': 'WMS change request submitted. Awaiting IT sprint allocation.',
        'follow_up_by': 'Sarah',
    },
    {
        'row_id': 49, 'issue_date': '05/03/2026',
        'issue': 'Outbound delivery documentation incomplete for customs clearance',
        'pareto_law': False, 'involved_departments': 'Logistics/Accounting',
        'issue_type': 'Problem', 'writer': 'Karim', 'reported_by': 'Logistics',
        'priority': 'High', 'status': 'In Progress',
        'responsible_section': 'Logistics', 'responsible_person': 'Karim',
        'section_team': 'Logistics',
        'impact': 'Shipment delays averaging 2-3 days. Customer SLA violations on 40% of cross-border orders.',
        'root_cause': 'No standardized checklist for export documentation. Different handlers follow different processes.',
        'action_plan': '1. Create mandatory export doc checklist\n2. Training session for all logistics staff\n3. System validation before gate release',
        'target_resolution_date': '2026-04-20',
        'progress_note': 'Checklist template drafted, under review by compliance team.',
        'follow_up_by': 'Karim',
    },
    {
        'row_id': 50, 'issue_date': '08/03/2026',
        'issue': 'ERP system response time degraded during peak hours',
        'pareto_law': True, 'involved_departments': 'IT/All',
        'issue_type': 'Issue', 'writer': 'IT Admin', 'reported_by': 'All Departments',
        'priority': 'High', 'status': 'In Progress',
        'responsible_section': 'IT', 'responsible_person': 'IT Admin',
        'section_team': 'IT Support',
        'impact': 'System unavailable or very slow 9am-12pm and 4pm-6pm. Affects all 45 users. 30% productivity loss estimated.',
        'root_cause': 'Database connection pool exhausted during peak load. Query optimization not done since 2024.',
        'action_plan': '1. Increase DB connection pool size\n2. Optimize top 10 slow queries\n3. Add caching layer for frequently accessed reports',
        'target_resolution_date': '2026-04-15',
        'progress_note': 'Connection pool increased from 10 to 50. Still optimizing queries.',
    },
    {
        'row_id': 51, 'issue_date': '10/03/2026',
        'issue': 'Procurement approval cycle exceeds 5 days for urgent purchases',
        'pareto_law': False, 'involved_departments': 'Procurement/Finance',
        'issue_type': 'Problem', 'writer': 'Finance', 'reported_by': 'Procurement',
        'priority': 'Medium', 'status': 'In Progress',
        'responsible_section': 'Finance', 'responsible_person': 'Finance Manager',
        'section_team': 'Finance',
        'impact': 'Operational delays when critical parts unavailable. 3 production stoppages last quarter.',
        'root_cause': 'Approval matrix requires sign-off from 4 levels even for small purchases under AED 5,000.',
        'action_plan': '1. Revise approval matrix: purchases < AED 5,000 need only 2 approvals\n2. Create emergency purchase fast-track process',
        'target_resolution_date': '2026-05-01',
        'progress_note': 'Draft approval matrix revision submitted to management for review.',
    },

    # ── Pending Review issues ──
    {
        'row_id': 52, 'issue_date': '15/02/2026',
        'issue': 'Customer invoice reconciliation discrepancies in February',
        'pareto_law': True, 'involved_departments': 'Accounting/Sales',
        'issue_type': 'Problem', 'writer': 'Accounting', 'reported_by': 'Accounting Team',
        'priority': 'High', 'status': 'Pending Review',
        'responsible_section': 'Accounting', 'responsible_person': 'Chief Accountant',
        'section_team': 'Finance',
        'impact': 'AED 85,000 in disputed invoices. Risk of late payment penalties and customer relationship damage.',
        'root_cause': 'Manual reconciliation process. Sales team not updating delivery confirmation before invoicing.',
        'action_plan': '1. Automated invoice matching implemented in ERP\n2. New mandatory delivery-confirm step added\n3. Training for sales team completed',
        'target_resolution_date': '2026-03-31',
        'progress_note': 'All identified discrepancies resolved. Automated matching deployed to production. Submitted for management review.',
        'follow_up_by': 'CFO',
    },
    {
        'row_id': 53, 'issue_date': '20/02/2026',
        'issue': 'Non-compliance with UAE Labour Law leave tracking requirements',
        'pareto_law': False, 'involved_departments': 'HR/Legal',
        'issue_type': 'Issue', 'writer': 'HR Manager', 'reported_by': 'HR',
        'priority': 'High', 'status': 'Pending Review',
        'responsible_section': 'HR', 'responsible_person': 'HR Manager',
        'section_team': 'HR',
        'impact': 'Potential regulatory fines up to AED 50,000. Audit risk identified during Q1 compliance review.',
        'root_cause': 'Leave balances not updated in real-time. Annual leave accrual calculation method outdated.',
        'action_plan': '1. Updated leave module with correct UAE Labour Law calculations\n2. Retroactive correction of all employee leave balances\n3. Process document updated',
        'target_resolution_date': '2026-03-15',
        'progress_note': 'Leave module updated and tested. All balances corrected. Legal review completed. Pending final approval.',
        'follow_up_by': 'CEO',
    },

    # ── Backlog issues ──
    {
        'row_id': 54, 'issue_date': '01/02/2026',
        'issue': 'Mobile app for field sales team not available',
        'pareto_law': False, 'involved_departments': 'Sales/IT',
        'issue_type': 'Suggestion', 'writer': 'Sales Director', 'reported_by': 'Sales Team',
        'priority': 'Medium', 'status': 'Backlog',
        'responsible_section': 'IT', 'responsible_person': '',
        'section_team': '',
        'impact': 'Sales team cannot access customer data or create orders while on customer visits. Manual process wastes 2+ hours/day per rep.',
        'root_cause': '',
        'action_plan': '',
        'target_resolution_date': '',
    },
    {
        'row_id': 55, 'issue_date': '10/02/2026',
        'issue': 'Barcode scanner replacement needed in Warehouse Zone B',
        'pareto_law': False, 'involved_departments': 'Warehouse/IT',
        'issue_type': 'Issue', 'writer': 'Warehouse Supervisor', 'reported_by': 'Ali',
        'priority': 'Medium', 'status': 'Backlog',
        'responsible_section': 'IT', 'responsible_person': '',
        'section_team': '',
        'impact': '3 of 8 scanners malfunctioning. Work slowed by 25% in Zone B.',
        'root_cause': 'Equipment age: scanners are 5+ years old, beyond useful life.',
        'action_plan': '',
        'target_resolution_date': '',
    },
    {
        'row_id': 56, 'issue_date': '12/02/2026',
        'issue': 'Customer portal integration with ERP needed for self-service order tracking',
        'pareto_law': False, 'involved_departments': 'IT/Sales/Customer Service',
        'issue_type': 'Suggestion', 'writer': 'CTO', 'reported_by': 'Customer Service',
        'priority': 'Low', 'status': 'Backlog',
        'responsible_section': 'IT', 'responsible_person': '',
        'section_team': '',
        'impact': 'Customer service team receives 50+ order status calls/day. Estimated 3 hours/day that could be automated.',
        'root_cause': '',
        'action_plan': '',
    },

    # ── Resolved issues ──
    {
        'row_id': 57, 'issue_date': '01/01/2026',
        'issue': 'Inventory count discrepancy in Ras Al Khor warehouse - January audit',
        'pareto_law': True, 'involved_departments': 'Warehouse/Accounting',
        'issue_type': 'Problem', 'writer': 'Warehouse Manager', 'reported_by': 'Internal Audit',
        'priority': 'High', 'status': 'Resolved',
        'responsible_section': 'Warehouse', 'responsible_person': 'Warehouse Manager',
        'section_team': 'Warehouse Ops',
        'impact': 'AED 23,000 inventory variance found. Audit report flags as high risk.',
        'root_cause': 'Physical count not reconciled with system within 24 hours. Multiple unrecorded adjustments.',
        'action_plan': '1. Daily physical-vs-system reconciliation implemented\n2. Adjustment authorisation workflow added\n3. Staff training on proper inventory procedures completed',
        'target_resolution_date': '2026-02-15',
        'progress_note': 'All variances investigated and adjusted. Process controls in place. Root cause documented.',
        'follow_up_by': 'CFO',
    },
    {
        'row_id': 58, 'issue_date': '10/01/2026',
        'issue': 'Supplier payment delays causing supply chain disruptions',
        'pareto_law': False, 'involved_departments': 'Finance/Procurement',
        'issue_type': 'Problem', 'writer': 'Procurement', 'reported_by': 'Procurement Manager',
        'priority': 'High', 'status': 'Resolved',
        'responsible_section': 'Finance', 'responsible_person': 'CFO',
        'section_team': 'Finance',
        'impact': 'Key supplier paused deliveries for 1 week. Production impacted. AED 40,000 emergency purchase premium paid.',
        'root_cause': 'Payment approval process not aligned with supplier payment terms. Finance team not notified of due dates.',
        'action_plan': '1. Automated payment due-date alerts to Finance\n2. Approval SLA set to 48 hours\n3. Supplier payment calendar integrated with ERP',
        'target_resolution_date': '2026-02-01',
        'progress_note': 'Automated alerts deployed. SLA met for last 6 weeks. Supplier relationship restored.',
        'follow_up_by': 'CFO',
    },
    {
        'row_id': 59, 'issue_date': '15/01/2026',
        'issue': 'Temperature log non-compliance in cold storage area',
        'pareto_law': False, 'involved_departments': 'Warehouse/Quality',
        'issue_type': 'Problem', 'writer': 'Quality Manager', 'reported_by': 'QC Team',
        'priority': 'Medium', 'status': 'Resolved',
        'responsible_section': 'Warehouse', 'responsible_person': 'Cold Store Supervisor',
        'section_team': 'Warehouse Ops',
        'impact': 'Risk of product spoilage and non-compliance with food safety standards.',
        'root_cause': 'Manual temperature logging process. Staff forgot to log during busy periods.',
        'action_plan': '1. Automated IoT temperature sensors installed\n2. Alerts configured for out-of-range readings\n3. Manual log requirement replaced with automated system',
        'target_resolution_date': '2026-02-28',
        'progress_note': 'IoT system installed and running for 30 days without issues. Validated by QC team.',
        'follow_up_by': 'Quality Manager',
    },

    # ── Closed issues ──
    {
        'row_id': 60, 'issue_date': '01/10/2025',
        'issue': 'System login page not accessible for some users after password reset',
        'pareto_law': False, 'involved_departments': 'IT',
        'issue_type': 'Problem', 'writer': 'IT Admin', 'reported_by': 'Multiple Users',
        'priority': 'High', 'status': 'Closed',
        'responsible_section': 'IT', 'responsible_person': 'IT Admin',
        'section_team': 'IT Support',
        'impact': '12 users unable to access system for 4 hours. Operations severely impacted.',
        'root_cause': 'Password reset script had a bug that corrupted session tokens.',
        'action_plan': 'Bug fixed in password reset script. Session cleanup script ran. All affected users notified and re-enabled.',
        'target_resolution_date': '2025-10-02',
        'progress_note': 'Issue fully resolved within 24 hours. All users able to log in. Patch deployed.',
        'follow_up_by': 'CTO',
        'final_status': 'Resolved & Verified',
    },
    {
        'row_id': 61, 'issue_date': '15/10/2025',
        'issue': 'Duplicate customer records causing incorrect AR statements',
        'pareto_law': False, 'involved_departments': 'Accounting/Sales',
        'issue_type': 'Problem', 'writer': 'Accounting', 'reported_by': 'Finance Team',
        'priority': 'Medium', 'status': 'Closed',
        'responsible_section': 'Accounting', 'responsible_person': 'AR Manager',
        'section_team': 'Finance',
        'impact': '23 customers had duplicate accounts. Statements sent to wrong contacts. Customer confusion.',
        'root_cause': 'No unique validation on customer creation. System allowed same email/trade license for multiple accounts.',
        'action_plan': '1. Duplicate records merged\n2. Unique constraint added on trade license and email\n3. Data quality check automated monthly',
        'target_resolution_date': '2025-11-01',
        'progress_note': 'All duplicates resolved. System constraint applied. No new duplicates in 3 months.',
        'follow_up_by': 'CFO',
        'final_status': 'Closed - Permanent Fix Applied',
    },
]
