"""Fix 198 Persian SAME_AS_KEY entries with proper Persian translations."""
with open('C:/Users/sdads/WHDASH/translations.py', 'r', encoding='utf-8') as f:
    lines = f.read().split('\n')

# Comprehensive Persian translations for the 198 missing keys
FA_FIXES = {
    # Quick Tools
    'add_current_page': 'افزودن صفحه جاری',
    'add_favorite': 'افزودن به علاقه‌مندی‌ها',
    'add_favorites_hint': 'برای افزودن صفحات کلیک کنید +',
    'add_note': 'افزودن یادداشت',
    'add_reminder': 'افزودن یادآوری',
    'autosave_notes': 'ذخیره خودکار یادداشت‌ها',
    'backspace': 'پاک کردن',
    'biweekly': 'دو هفته‌ای',
    'bookmark_added': 'نشانه اضافه شد',
    'bookmark_removed': 'نشانه حذف شد',
    'calculator': 'ماشین حساب',
    'clear': 'پاک کردن',
    'close_tools': 'بستن ابزارها',
    'compact_mode': 'حالت فشرده',
    'copy_result': 'کپی نتیجه',
    'create_issue': 'ایجاد مشکل',
    'create_task': 'ایجاد وظیفه',
    'daily': 'روزانه',
    'delete_note': 'حذف یادداشت',
    'division_by_zero': 'تقسیم بر صفر ممکن نیست',
    'edit_note': 'ویرایش یادداشت',
    'edit_reminder': 'ویرایش یادآوری',
    'equals': 'برابر است با',
    'expression_error': 'خطای عبارت',
    'favorites': 'علاقه‌مندی‌ها',
    'flow': 'جریان',
    'flow_add_members': 'افزودن اعضا',
    'flow_admin': 'مدیر',
    'flow_all_caught_up': 'همه پیام‌ها را دیده‌اید!',
    'flow_app_name': 'جریان',
    'flow_appear_offline': 'آفلاین نمایش دادن',
    'flow_audio_call': 'تماس صوتی',
    'flow_auto_reply': 'پاسخ خودکار',
    'flow_away': 'دور از دسترس',
    'flow_busy': 'مشغول',
    'flow_calls': 'تماس‌ها',
    'flow_category': 'دسته‌بندی',
    'flow_channels': 'کانال‌ها',
    'flow_chat': 'گفتگو',
    'flow_co_host': 'میزبان مشترک',
    'flow_copy': 'کپی',
    'flow_create_channel': 'ایجاد کانال',
    'flow_create_first_channel': 'برای شروع همکاری اولین کانال خود را ایجاد کنید',
    'flow_create_first_group': 'برای شروع همکاری با تیم، یک گروه ایجاد کنید',
    'flow_create_group': 'ایجاد گروه',
    'flow_created_by': 'ایجاد شده توسط',
    'flow_delete': 'حذف',
    'flow_delete_for_everyone': 'حذف برای همه',
    'flow_delete_for_me': 'حذف برای من',
    'flow_description': 'توضیحات',
    'flow_edit': 'ویرایش',
    'flow_editing': 'در حال ویرایش',
    'flow_enter_send': 'Enter برای ارسال',
    'flow_file_too_large': 'فایل بیش از حد بزرگ است (حداکثر 2 گیگابایت)',
    'flow_forward': 'ارسال',
    'flow_group': 'گروه',
    'flow_groups': 'گروه‌ها',
    'flow_image': 'تصویر',
    'flow_in_meeting': 'در جلسه',
    'flow_join_channel': 'پیوستن به کانال',
    'flow_join_meeting': 'پیوستن به جلسه',
    'flow_last_seen': 'آخرین حضور',
    'flow_leave_channel': 'ترک کانال',
    'flow_leave_group': 'ترک گروه',
    'flow_leave_meeting': 'ترک جلسه',
    'flow_mark_read': 'علامت به عنوان خوانده شده',
    'flow_members': 'اعضا',
    'flow_message_deleted': 'حذف شده',
    'flow_message_edited': 'ویرایش شده',
    'flow_messages': 'پیام‌ها',
    'flow_mute': 'بی‌صدا کردن',
    'flow_new_chat': 'گفتگوی جدید',
    'flow_no_calls': 'بدون تاریخچه تماس',
    'flow_no_channels': 'هنوز کانالی نیست',
    'flow_no_conversations': 'هنوز گفتگویی نیست',
    'flow_no_groups': 'هنوز گروهی نیست',
    'flow_no_media': 'هنوز رسانه‌ای نیست',
    'flow_no_meetings': 'جلسه‌ای وجود ندارد',
    'flow_no_messages': 'هنوز پیامی نیست',
    'flow_no_notifications': 'بدون اعلان‌ها',
    'flow_no_results': 'نتیجه‌ای یافت نشد',
    'flow_no_saved': 'بدون پیام ذخیره شده',
    'flow_notifications': 'اعلان‌ها',
    'flow_offline': 'آفلاین',
    'flow_online': 'آنلاین',
    'flow_online_status': 'وضعیت آنلاین',
    'flow_private_chats': 'گفتگوهای خصوصی',
    'flow_profile': 'پروفایل',
    'flow_react': 'واکنش',
    'flow_read': 'خوانده شده',
    'flow_recent': 'اخیر',
    'flow_reminder_set': 'یادآوری تنظیم شد',
    'flow_reminder_you_will_be_notified': 'به شما اطلاع داده خواهد شد',
    'flow_reminders': 'یادآوری‌ها',
    'flow_remove_member': 'حذف عضو',
    'flow_reply': 'پاسخ',
    'flow_reply_to': 'پاسخ به',
    'flow_save': 'ذخیره',
    'flow_save_hint': 'پیام‌های مهم را ذخیره کنید تا بعداً پیدایشان کنید',
    'flow_saved_messages': 'پیام‌های ذخیره شده',
    'flow_search': 'جستجو',
    'flow_send': 'ارسال',
    'flow_send_first_message': 'برای شروع مکالمه یک پیام ارسال کنید',
    'flow_set_reminder': 'تنظیم یادآوری',
    'flow_set_reminders_hint': 'روی پیام‌ها یادآوری تنظیم کنید تا بعداً به شما اطلاع داده شود',
    'flow_settings': 'تنظیمات',
    'flow_shared_media': 'رسانه‌های به اشتراک گذاشته شده',
    'flow_shift_enter': 'Shift + Enter برای خط جدید',
    'flow_start_call_hint': 'از هر گفتگویی تماس بگیرید',
    'flow_start_instant_meeting': 'شروع جلسه فوری',
    'flow_start_meeting_hint': 'یک جلسه فوری شروع کنید',
    'flow_start_new_chat': 'برای شروع پیام‌رسانی یک گفتگوی جدید شروع کنید',
    'flow_status_message': 'پیام وضعیت',
    'flow_stopped': 'متوقف شده',
    'flow_typing': 'در حال تایپ...',
    'flow_unmute': 'صدادار کردن',
    'flow_upload_error': 'خطا در آپلود',
    'flow_upload_file': 'آپلود فایل',
    'flow_video_call': 'تماس تصویری',
    'flow_video_off': 'دوربین خاموش',
    'flow_video_on': 'دوربین روشن',
    'flow_voice_note': 'یادداشت صوتی',
    'flow_voice_note_recording': 'در حال ضبط...',
    'flow_you_were_removed': 'شما حذف شدید',
    'in_1_hour': 'در 1 ساعت',
    'invalid_expression': 'عبارت نامعتبر',
    'issue_category': 'دسته‌بندی مشکل',
    'issue_created': 'مشکل ایجاد شد',
    'issue_description': 'توضیحات مشکل',
    'issue_priority': 'اولویت مشکل',
    'issue_title': 'عنوان مشکل',
    'issue_type': 'نوع مشکل',
    'mark_done': 'علامت به عنوان انجام شده',
    'next_week': 'هفته آینده',
    'no_favorites': 'بدون علاقه‌مندی',
    'no_favorites_desc': 'صفحه‌ای به علاقه‌مندی‌ها اضافه نشده است',
    'no_notes': 'بدون یادداشت',
    'no_notes_desc': 'یادداشتی ذخیره نشده است',
    'no_reminders': 'بدون یادآوری',
    'no_reminders_desc': 'یادآوری تنظیم نشده است',
    'note_placeholder': 'یادداشت خود را بنویسید...',
    'open_tools': 'باز کردن ابزارها',
    'pin_note': 'پین کردن یادداشت',
    'priority_critical': 'بحرانی',
    'priority_high': 'بالا',
    'priority_low': 'پایین',
    'priority_medium': 'متوسط',
    'remind_at': 'یادآوری در',
    'remind_me': 'یادآوری به من',
    'reminder_set': 'یادآوری تنظیم شد',
    'reminders': 'یادآوری‌ها',
    'remove_favorite': 'حذف از علاقه‌مندی‌ها',
    'result_copied': 'نتیجه کپی شد',
    'shortcuts': 'میانبرها',
    'show_calculator': 'نمایش ماشین حساب',
    'show_favorites': 'نمایش علاقه‌مندی‌ها',
    'show_issues': 'نمایش مشکلات',
    'show_notes': 'نمایش یادداشت‌ها',
    'show_reminders': 'نمایش یادآوری‌ها',
    'show_tasks': 'نمایش وظایف',
    'snooze': 'به تعویق انداختن',
    'snooze_1_hour': '۱ ساعت به تعویق بینداز',
    'task_assign_self': 'تعیین به خودم',
    'task_assign_to': 'واگذاری به',
    'task_created': 'وظیفه با موفقیت ایجاد شد',
    'task_description': 'توضیحات',
    'task_due_date': 'تاریخ سررسید',
    'task_priority': 'اولویت',
    'task_title': 'عنوان وظیفه',
    'tomorrow': 'فردا',
    'tonight': 'امشب',
    'tools_calculations': 'محاسبات',
    'tools_favorites': 'علاقه‌مندی‌ها',
    'tools_issues': 'مشکلات',
    'tools_notes': 'یادداشت‌ها',
    'tools_reminders': 'یادآوری‌ها',
    'tools_settings': 'تنظیمات',
    'tools_tasks': 'وظایف',
    'type_issue': 'مشکل را تایپ کنید',
    'type_problem': 'مشکل:',
    'type_suggestion': 'پیشنهاد:',
    'unpin_note': 'برداشتن پین یادداشت',
}

# Find FA section
fa_start = None
for i, line in enumerate(lines):
    if line.strip().startswith("'fa':"):
        fa_start = i
        break

print(f"FA section starts at line {fa_start+1}")

# Apply fixes
changes = 0
for i in range(fa_start, min(fa_start + 1000, len(lines))):
    line = lines[i]
    stripped = line.strip()
    for key, persian_val in FA_FIXES.items():
        if stripped.startswith(f"'{key}':"):
            indent = len(line) - len(line.lstrip())
            new_line = f"{' ' * indent}'{key}': '{persian_val}',"
            lines[i] = new_line
            changes += 1
            break
    # Stop if we hit next language
    if "'ar':" in lines[i] or "'ru':" in lines[i]:
        break

print(f"Fixed {changes} Persian keys")

with open('C:/Users/sdads/WHDASH/translations.py', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print("Written to translations.py")